### ISSUE TITLE
It's not working in my computer...

### ISSUE THREAD

**Issue by RamazanM** [mesutpiskin/wikipediaZeroExtension#1]
![screenshot from 2017-11-12 23 56 27](https://user-images.githubusercontent.com/7129356/32703376-e72dfaac-c805-11e7-80d8-ade26fd4b580.png)
It just stay in this screen not update the url. I changed the code and now it's working for me...
If it's not just my problem i can send you a pull request. Can you check this?

**Comment by SamiRenkyorganci** [comment]
It's not working on my pc too... :(

**Comment by mesutpiskin** [comment]
It's a good news that you've made improvements. You can send your pull request.
